USE [QLPG]
GO

/****** Object:  Trigger [dbo].[UPDATE_STATE]    Script Date: 11/27/2022 5:50:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[UPDATE_STATE] ON [dbo].[PHIEUTHUTIEN] AFTER INSERT
AS
BEGIN
	DECLARE @NGAYBD DATE
	SET @NGAYBD = (SELECT NGAYTHU FROM inserted)
	UPDATE PHIEUDANGKY
	SET TRANGTHAI = N'Đã kích hoạt',
	NGAYBD = @NGAYBD,
	NGAYKT = (SELECT DATEADD(DAY, SONGAYSUDUNG, @NGAYBD) 
	FROM DICHVU DV, PHIEUDANGKY PDK, inserted WHERE PDK.MAPDK = inserted.MAPDK AND PDK.MADV = DV.MADV)
	WHERE MAPDK = (SELECT MAPDK FROM inserted)
END
GO


